### ISSUE TITLE
ValueError: missing values must be missing in the same location both left and right sides

### ISSUE THREAD

**Issue by XiangBu** [MLD3/JCO_CCI_aGVHD_prediction#5]
sorry to bother. When I try to run 1_Extract_Features.ipynb  to get  df_features, ValueError: missing values must be missing in the same location both left and right sides
![image](https://user-images.githubusercontent.com/46986985/117153617-bc1fff00-aded-11eb-91eb-680ca018aad7.png)

It seems inf in the dataframe causing the problem when using pd.qcut. However, I can't solve it. Please help me. THANKS!

**Comment by shengpu-tang** [comment]
Could you send me what version of python you're using, and the relevant package versions (numpy, pandas, etc)? I can help take a closer look.

**Comment by XiangBu** [comment]
Python 3.8.5    
pandas 1.2.4   
numpy 1.19.2
matplotlib  3.3.2
scipy 1.5.2
seaborn 0.11.0
tqdm    4.50.2
tsfresh   0.18.0
scikit-learn   0.22
joblib   0.17.0

**Comment by shengpu-tang** [comment]
Hello, I found that with tsfresh 0.18.0, the sample_entropy column is not correctly computed and it outputs nan/inf values. I was able to run the code with tsfresh 0.15.0. Please try installing this version and let me know if it fixes things. 

```
pip install tsfresh==0.15.0
```

**Comment by XiangBu** [comment]
> Hello, I found that with tsfresh 0.18.0, the sample_entropy column is not correctly computed and it outputs nan/inf values. I was able to run the code with tsfresh 0.15.0. Please try installing this version and let me know if it fixes things.
> 
> ```
> pip install tsfresh==0.15.0
> ```

yes, it works well. Thanks a lot!
